import React from 'react';
import { Plus, Bell, Search, ChevronDown, ClipboardList, Users, Building2, ChartPie as PieChart, Settings, Circle as HelpCircle, Shield, MessageSquare, Calendar, X, Send, Clock, CreditCard as Edit, Trash2, Loader as Loader2, CircleCheck as CheckCircle, TriangleAlert as AlertTriangle, UserPlus, ChevronLeft, ChevronRight, ListFilter as Filter, CircleUser as UserCircle, LogOut, Camera, Archive, FilePlus, Sun, Moon, Menu, Paperclip, Download, LayoutGrid, List, Copy } from 'lucide-react';

type IconProps = React.ComponentProps<typeof Plus>;

export const PlusIcon: React.FC<IconProps> = (props) => <Plus {...props} />;
export const BellIcon: React.FC<IconProps> = (props) => <Bell {...props} />;
export const SearchIcon: React.FC<IconProps> = (props) => <Search {...props} />;
export const ChevronDownIcon: React.FC<IconProps> = (props) => <ChevronDown {...props} />;
export const ClipboardListIcon: React.FC<IconProps> = (props) => <ClipboardList {...props} />;
export const UsersIcon: React.FC<IconProps> = (props) => <Users {...props} />;
export const BuildingLibraryIcon: React.FC<IconProps> = (props) => <Building2 {...props} />;
export const ChartPieIcon: React.FC<IconProps> = (props) => <PieChart {...props} />;
export const Cog6ToothIcon: React.FC<IconProps> = (props) => <Settings {...props} />;
export const QuestionMarkCircleIcon: React.FC<IconProps> = (props) => <HelpCircle {...props} />;
export const ShieldCheckIcon: React.FC<IconProps> = (props) => <Shield {...props} />;
export const ChatBubbleLeftRightIcon: React.FC<IconProps> = (props) => <MessageSquare {...props} />;
export const CalendarDaysIcon: React.FC<IconProps> = (props) => <Calendar {...props} />;
export const XMarkIcon: React.FC<IconProps> = (props) => <X {...props} />;
export const PaperAirplaneIcon: React.FC<IconProps> = (props) => <Send {...props} />;
export const ClockIcon: React.FC<IconProps> = (props) => <Clock {...props} />;
export const PencilIcon: React.FC<IconProps> = (props) => <Edit {...props} />;
export const TrashIcon: React.FC<IconProps> = (props) => <Trash2 {...props} />;
export const LoadingSpinner: React.FC<IconProps> = (props) => <Loader2 className="animate-spin" {...props} />;
export const CheckCircleIcon: React.FC<IconProps> = (props) => <CheckCircle {...props} />;
export const ExclamationTriangleIcon: React.FC<IconProps> = (props) => <AlertTriangle {...props} />;
export const UserGroupIcon: React.FC<IconProps> = (props) => <UserPlus {...props} />;
export const ChevronLeftIcon: React.FC<IconProps> = (props) => <ChevronLeft {...props} />;
export const ChevronRightIcon: React.FC<IconProps> = (props) => <ChevronRight {...props} />;
export const FunnelIcon: React.FC<IconProps> = (props) => <Filter {...props} />;
export const UserCircleIcon: React.FC<IconProps> = (props) => <UserCircle {...props} />;
export const ArrowRightOnRectangleIcon: React.FC<IconProps> = (props) => <LogOut {...props} />;
export const CameraIcon: React.FC<IconProps> = (props) => <Camera {...props} />;
export const ArchiveIcon: React.FC<IconProps> = (props) => <Archive {...props} />;
export const DocumentPlusIcon: React.FC<IconProps> = (props) => <FilePlus {...props} />;
export const SunIcon: React.FC<IconProps> = (props) => <Sun {...props} />;
export const MoonIcon: React.FC<IconProps> = (props) => <Moon {...props} />;
export const Bars3Icon: React.FC<IconProps> = (props) => <Menu {...props} />;
export const PaperclipIcon: React.FC<IconProps> = (props) => <Paperclip {...props} />;
export const DownloadIcon: React.FC<IconProps> = (props) => <Download {...props} />;
export const Squares2X2Icon: React.FC<IconProps> = (props) => <LayoutGrid {...props} />;
export const ListBulletIcon: React.FC<IconProps> = (props) => <List {...props} />;
export const DocumentDuplicateIcon: React.FC<IconProps> = (props) => <Copy {...props} />;